# https://pwa.spomky-labs.com/the-manifest/application-information
pwa:
  manifest:
    enabled: true
    name: "My PWA"
    short_name: "PWA"
    start_url: "/admin"
    display: "standalone"
    background_color: "#ffffff"
    theme_color: "#4285f4"
